[workspace.package]
version = "0.2.0"
authors = ["RustPython Team", "Charlie Marsh <charlie.r.marsh@gmail.com>"]
edition = "2021"
rust-version = "1.67.1"
description = "Python parser and its dependencies."
repository = "https://github.com/RustPython/Parser"
license = "MIT"
include = ["LICENSE", "Cargo.toml", "src/**/*.rs"]

[workspace]
resolver = "2"
members = [
    "ruff_python_ast", "literal", "ruff_python_parser", "ruff_text_size",
]

[workspace.dependencies]
ruff_python_ast = { path = "ruff_python_ast" }
rustpython-literal = { path = "literal" }
ruff_text_size = { path = "ruff_text_size" }

anyhow = "1.0.45"
bitflags = "2.3.3"
cfg-if = "1.0"
insta = "1.14.0"
itertools = "0.10.3"
is-macro = "0.2.2"
num-complex = "0.4.0"
num-bigint = "0.4.3"
num-traits = "0.2"
rand = "0.8.5"
serde = "1.0"
static_assertions = "1.1"
unicode_names2 = { version = "0.6.0", git = "https://github.com/youknowone/unicode_names2.git", rev = "4ce16aa85cbcdd9cc830410f1a72ef9a235f2fde" }

[profile.dev.package."*"]
opt-level = 3

[profile.bench]
lto = "thin"
codegen-units = 1
opt-level = 3

[profile.release]
lto = "thin"
